### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by SupremeSports** [tmonck/clean_up_snapshots#16] opened 2021-04-09 01:42 UTC
Getting this warning:

```
2021-04-08 21:10:54 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'clean_up_snapshots_service'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'clean_up_snapshots_service'
```

**Comment by tmonck** [comment] 2021-06-01 23:42
Just released a new version 0.8. Sorry it took me so long to get to this. Please let me know if the issue isn't resolved.

**Comment by gateriderz** [comment] 2021-06-02 13:38
I think there's a typo in the manifest.json file.
There should be "comma" instead of "period"

> "requirements": [],

**Comment by jamespreedy** [comment] 2021-06-02 19:19
Interestingly, I changed that period to a comma, and I still get the below on reboot.

`<Integration tmonck/clean_up_snapshots> Could not read manifest.json [Expecting ',' delimiter: line 7 column 23 (char 222)]`

**Comment by inverse** [comment] 2021-06-02 20:02
Changing it to a `,` fixed it for me.

**Comment by jamespreedy** [comment] 2021-06-02 20:05
Thats odd, I changed mine so it looked like the below.

![Screenshot 2021-06-02 at 9 04 25 pm](https://user-images.githubusercontent.com/559531/120545177-3a1ff780-c3e6-11eb-8349-8ecce2ae3c85.png)

but I still get this on boot.

![Screenshot 2021-06-02 at 9 04 50 pm](https://user-images.githubusercontent.com/559531/120545191-41470580-c3e6-11eb-9e37-588fc8b833b6.png)

Was there a cache or anything you had to clear?

**Comment by inverse** [comment] 2021-06-02 20:09
I did remove and reinstall from HACS between manually modifying. Aside that just a restart of system (not the host).

**Comment by tmonck** [comment] 2021-06-02 20:17
Shoot, I'll get this fixed in about an hour. Thanks for the details.

**Comment by inverse** [comment] 2021-06-02 20:26
@tmonck fixed in https://github.com/tmonck/clean_up_snapshots/pull/19

**Comment by tmonck** [comment] 2021-06-02 21:37
Thanks @inverse. Just created a new release 0.8.1.

**Closed by tmonck** 2021-06-02 21:37 UTC
Labels: bug
